# Generated by Django 4.0.6 on 2022-07-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value_before_comma', models.PositiveSmallIntegerField()),
                ('value_after_comma', models.PositiveSmallIntegerField()),
                ('nominal', models.PositiveIntegerField()),
                ('valute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.valute')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
