# Generated by Django 4.0.6 on 2022-07-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='value_after_comma',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='value_before_comma',
            field=models.PositiveIntegerField(),
        ),
    ]
