# Generated by Django 4.0.6 on 2022-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_rate_value_after_comma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='value_after_comma',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='value_before_comma',
        ),
        migrations.AddField(
            model_name='rate',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
