networks:
  app:
    driver: bridge

services:
  django:
    container_name: django
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - builds_db
    environment:
      - POSTGRES_DB=buildsio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - app

  builds_db:
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=buildsio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - app

  vue:
    container_name: vue
    restart: always
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - django
    networks:
      - app
